###
POST http://localhost:3012/auth/add
Content-Type: application/json

{
  "login": "zahra",
  "password": "admin1234"
}

###
POST http://localhost:1337/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTZhMDAyNWFlMWFjYzhlYmZlM2RkOCIsInVzZXJuYW1lIjoidG9tdG9tMSIsImVtYWlsIjoidGhvbWFzMUBnbWFpbC5jb20iLCJpYXQiOjE3MDU0MTg4MDAsImV4cCI6MTcwNTQyMjQwMH0.x3Ud5sstX8rN39w9_jDK314sHYtwtmj5PFKeJg2nUjk

{
  "currentPassword": "admin1234",
  "password": "tomtom1234",
  "passwordConfirmation": "tomtom1234"
}

###
POST http://localhost:3012/auth/connect
Content-Type: application/json

{
   "login": "zahra14",
  "password": "zahra14"
}

###
POST http://localhost:1337/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTZhMDAyNWFlMWFjYzhlYmZlM2RkOCIsInVzZXJuYW1lIjoidG9tdG9tMSIsImVtYWlsIjoidGhvbWFzMUBnbWFpbC5jb20iLCJpYXQiOjE3MDU0MTg4MDAsImV4cCI6MTcwNTQyMjQwMH0.x3Ud5sstX8rN39w9_jDK314sHYtwtmj5PFKeJg2nUjk

###
GET http://localhost:3012/users/check-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTk4MTY1MmJlYmU0ZDI0MGQwNGYwMCIsImxvZ2luIjoiemFocmExNCIsImlhdCI6MTcwNTY1MTYwOSwiZXhwIjoxNzA1NjU1MjA5fQ.1ri9kEB8bjeO0X9EUZnJ0848yLjQZv6Er2M5bXO9l5w
###
GET http://localhost:3012/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTk4MTY1MmJlYmU0ZDI0MGQwNGYwMCIsImxvZ2luIjoiemFocmExNCIsImlhdCI6MTcwNTY3MDA5MCwiZXhwIjoxNzA1NjczNjkwfQ.qPJUXcuNOgtx8TanK7Gvt6mZVthJrEkNybipV1IrArw

###

POST http://localhost:3012/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTk4MTY1MmJlYmU0ZDI0MGQwNGYwMCIsImxvZ2luIjoiemFocmExNCIsImlhdCI6MTcwNTY3MDI1NCwiZXhwIjoxNzA1NjczODU0fQ.kA1elzFJZkcL7mqOiYWDDrwKUhoINXMfLzNOksqpHe8
Content-Type: application/json

{
  "joueur1": "zahra1",
  "joueur2": "zahra2",
  "winner": "zahra1",
  "bestTime": 100,
  "objective": 200
}

###
PUT http://localhost:3012/games/65aa7b615bdca3b4594e5af6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTk4MTY1MmJlYmU0ZDI0MGQwNGYwMCIsImxvZ2luIjoiemFocmExNCIsImlhdCI6MTcwNTY3MDI1NCwiZXhwIjoxNzA1NjczODU0fQ.kA1elzFJZkcL7mqOiYWDDrwKUhoINXMfLzNOksqpHe8
Content-Type: application/json

{
  "joueur1": "zahra4",
  "joueur2": "zahra3",
  "winner": "zahra3",
  "bestTime": 150,
  "objective": 250
}
###
GET  http://localhost:3012/games/65aa7cfb030382cb1d565057
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTk4MTY1MmJlYmU0ZDI0MGQwNGYwMCIsImxvZ2luIjoiemFocmExNCIsImlhdCI6MTcwNTY3MDI1NCwiZXhwIjoxNzA1NjczODU0fQ.kA1elzFJZkcL7mqOiYWDDrwKUhoINXMfLzNOksqpHe8
Content-Type: application/json

{
  "joueur1": "zahra4",
  "joueur2": "zahra3",
  "winner": "zahra3",
  "bestTime": 150,
  "objective": 250
}


###
DELETE  http://localhost:3012/games/65aa7b615bdca3b4594e5af6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTk4MTY1MmJlYmU0ZDI0MGQwNGYwMCIsImxvZ2luIjoiemFocmExNCIsImlhdCI6MTcwNTY3MDI1NCwiZXhwIjoxNzA1NjczODU0fQ.kA1elzFJZkcL7mqOiYWDDrwKUhoINXMfLzNOksqpHe8
Content-Type: application/json

{
  "joueur1": "zahra4",
  "joueur2": "zahra3",
  "winner": "zahra3",
  "bestTime": 150,
  "objective": 250
}


